services:
  - type: web
    name: UniQuest
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn telusko.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: uniquest-db
          property: connectionString

databases:
  - name: uniquest-db
    plan: free
    databaseName: uniquest
    user: uniquest